import { GameState } from "./GameState";

export const exampleState: GameState = [
  ["Bob", null, null, null, null, null, null, null, "Jose", null, null, null, null, null, "Jose", null, null, null, "Bob", null, null, null, null, null],
  [null, null, "Jose", null, null, null, "Bob", null, null, null, null, null, null, null, "Jose", null, null, null, "Bob", null, null, null, null, null],
  [null, null, "Jose", null, null, null, "Bob", null, null, null, null, null, null, null, null, "Jose", null, null, null, null, null, "Jose", null, null],
  ["Bob", null, null, null, null, null, null, null, "Jose", null, null, null, null, null, "Jose", null, null, null, "Bob", null, null, null, null, null],
  [null, null, "Jose", null, null, null, "Bob", null, null, null, null, null, null, null, "Jose", null, null, null, "Bob", null, null, null, null, null],
  [null, null, "Jose", null, null, null, "Bob", null, null, null, null, null, null, null, null, "Jose", null, null, null, null, null, "Jose", null, null],
  ["Bob", null, null, null, null, null, null, null, "Jose", null, null, null, null, null, "Jose", null, null, null, "Bob", null, null, null, null, null],
  [null, null, "Jose", null, null, null, "Bob", null, null, null, null, null, null, null, "Jose", null, null, null, "Bob", null, null, null, null, null],
  [null, null, "Jose", null, null, null, "Bob", null, null, null, null, null, null, null, null, "Jose", null, null, null, null, null, "Jose", null, null],
  ["Bob", null, null, null, null, null, null, null, "Jose", null, null, null, null, null, "Jose", null, null, null, "Bob", null, null, null, null, null],
  [null, null, "Jose", null, null, null, "Bob", null, null, null, null, null, null, null, "Jose", null, null, null, "Bob", null, null, null, null, null],
  [null, null, "Jose", null, null, null, "Bob", null, null, null, null, null, null, null, null, "Jose", null, null, null, null, null, "Jose", null, null],
  ["Bob", null, null, null, null, null, null, null, "Jose", null, null, null, null, null, "Jose", null, null, null, "Bob", null, null, null, null, null],
  [null, null, "Jose", null, null, null, "Bob", null, null, null, null, null, null, null, "Jose", null, null, null, "Bob", null, null, null, null, null],
  [null, null, "Jose", null, null, null, "Bob", null, null, null, null, null, null, null, null, "Jose", null, null, null, null, null, "Jose", null, null],
  ["Bob", null, null, null, null, null, null, null, "Jose", null, null, null, null, null, "Jose", null, null, null, "Bob", null, null, null, null, null],
  [null, null, "Jose", null, null, null, "Bob", null, null, null, null, null, null, null, "Jose", null, null, null, "Bob", null, null, null, null, null],
  [null, null, "Jose", null, null, null, "Bob", null, null, null, null, null, null, null, null, "Jose", null, null, null, null, null, "Jose", null, null],
  ["Bob", null, null, null, null, null, null, null, "Jose", null, null, null, null, null, "Jose", null, null, null, "Bob", null, null, null, null, null],
  [null, null, "Jose", null, null, null, "Bob", null, null, null, null, null, null, null, "Jose", null, null, null, "Bob", null, null, null, null, null],
  [null, null, "Jose", null, null, null, "Bob", null, null, null, null, null, null, null, null, "Jose", null, null, null, null, null, "Jose", null, null],
  ["Bob", null, null, null, null, null, null, null, "Jose", null, null, null, null, null, "Jose", null, null, null, "Bob", null, null, null, null, null],
  [null, null, "Jose", null, null, null, "Bob", null, null, null, null, null, null, null, "Jose", null, null, null, "Bob", null, null, null, null, null],
  [null, null, "Jose", null, null, null, "Bob", null, null, null, null, null, null, null, null, "Jose", null, null, null, null, null, "Jose", null, null],
];
